### ISSUE TITLE
Make = operator a friend function

### ISSUE THREAD

**Issue by joel-lilja** [joel-lilja/jstring#1]
Hey we are going to want to make it so char* = string is possible. We should refactor our = operator to work as a friend function  so we can overload it to make char* = string possible. 

-joel

**Comment by joel-lilja** [comment]
we won't be able to do that by making the function a friend. will have to use jstring::operator char*() since the assignment operator needs to be a non-static member function. having done a little research, I think it might be better to use a function like the string class in c++ uses, so we can do something like:

`char * newString = jstring.c_str()`

**Comment by freelinhummel** [comment]
oops, commented as you since I never closed the window.

**Comment by joel-lilja** [comment]
alright member function is is we decided
